sudo: required

branches:
    only:
        - master
        - develop
        - release-prod

services: docker

language: C

cache:
    yarn: true
    directories:
        - node_modules

script: ./travis-build.sh
