name: Deploy stage

on:
  push:
    branches:
      - master

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: "Set time zone to Europe/Helsinki"
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Helsinki"
      - name: Set current date to be accessible later with steps.date.outputs.date
        id: date
        run: echo "::set-output name=date::$(date +'%d.%m.%Y_%H:%M')"
      - uses: actions/checkout@v2
        with:
          ref: master
      - name: Build UI and publish Docker image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hsldevcom/jore-map-ui
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
          buildargs: APP_ENVIRONMENT=stage, APP_DOMAIN_NAME=${{ secrets.APP_DOMAIN_NAME }}, APP_BUILD_DATE=${{ steps.date.outputs.date }}
          tags: stage
      - name: Deploy with Gitlab CI
        run: curl -X POST -F token=${{ secrets.GITLAB_TRIGGER_TOKEN }} -F ref=master -F "variables[TARGET_ENV_STAGE]=TARGET_ENV_STAGE" https://gitlab.hsl.fi/api/v4/projects/231/trigger/pipeline
      - name: Notify of deployment
        uses: 8398a7/action-slack@v2
        if: always()
        with:
          status: ${{ job.status }}
          text: Jore-map STAGE deployment status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
