name: Test dev

on:
    pull_request:
        branches:
            - master

jobs:
    test-dev:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                  ref: master
            - uses: actions/setup-node@v1
              with:
                  node-version: '10.x'
            - name: Cypress tests
              uses: cypress-io/github-action@v1
              env:
                  CYPRESS_BASE_URL: https://dev.jore-map.hsl.fi
                  HSLID_CLIENT_ID: ${{ secrets.HSLID_CLIENT_ID }}
                  HSLID_CLIENT_SECRET: ${{ secrets.HSLID_CLIENT_SECRET }}
                  HSLID_CYPRESS_WRITE_ACCESS_USERNAME: ${{ secrets.HSLID_CYPRESS_WRITE_ACCESS_USERNAME }}
                  HSLID_CYPRESS_WRITE_ACCESS_PASSWORD: ${{ secrets.HSLID_CYPRESS_WRITE_ACCESS_PASSWORD }}
                  HSLID_CYPRESS_READ_ACCESS_USERNAME: ${{ secrets.HSLID_CYPRESS_READ_ACCESS_USERNAME }}
                  HSLID_CYPRESS_READ_ACCESS_PASSWORD: ${{ secrets.HSLID_CYPRESS_READ_ACCESS_PASSWORD }}
            - name: Upload screenshot artifacts
              uses: actions/upload-artifact@v1
              if: failure()
              with:
                  name: cypress-screenshots
                  path: cypress/screenshots
            - name: Upload video artifacts
              uses: actions/upload-artifact@v1
              if: always()
              with:
                  name: cypress-videos
                  path: cypress/videos
            - name: Notify of tests
              uses: 8398a7/action-slack@v2
              if: always()
              with:
                  status: ${{ job.status }}
                  text: Jore-map DEV E2E test status
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
