name: Test stage

on:
  pull_request:
    branches:
      - release-prod

jobs:
  test-stage:
    runs-on: ubuntu-latest
    steps:
      - name: "Set time zone to Europe/Helsinki"
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Helsinki"
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_E2E: true # Needed to tell babel.config to not load cypress breaking presets
          CYPRESS_BASE_URL: https://stage.jore-map.hsl.fi
          CYPRESS_HSLID_CLIENT_ID: ${{ secrets.CYPRESS_HSLID_CLIENT_ID }}
          CYPRESS_HSLID_CLIENT_SECRET: ${{ secrets.CYPRESS_HSLID_CLIENT_SECRET }}
          CYPRESS_HSLID_WRITE_ACCESS_USERNAME: ${{ secrets.CYPRESS_HSLID_WRITE_ACCESS_USERNAME }}
          CYPRESS_HSLID_WRITE_ACCESS_PASSWORD: ${{ secrets.CYPRESS_HSLID_WRITE_ACCESS_PASSWORD }}
          CYPRESS_HSLID_READ_ACCESS_USERNAME: ${{ secrets.CYPRESS_HSLID_READ_ACCESS_USERNAME }}
          CYPRESS_HSLID_READ_ACCESS_PASSWORD: ${{ secrets.CYPRESS_HSLID_READ_ACCESS_PASSWORD }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      - name: Upload screenshot artifacts
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      - name: Upload video artifacts
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      - name: Notify of tests
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          text: Jore-map STAGE E2E test status
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
